# Jekyll Resume Theme

# Site settings
title: Wenxuan Bao's Resume
email: baowenxuan@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Wenxuan Bao
job: student
location: Beijing, China
languages: Python
github_username:  baowenxuan
email_address: baowenxuan@gmail.com

# Build settings
markdown: kramdown
